name: Deploy MkDocs

on:
  push:
    branches:
      - v2
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: mkdocs build --strict

      - name: Deploy
        if: github.ref == 'refs/heads/v2'
        run: mkdocs gh-deploy --force
